
name: React Native APK Distribution

on:
  push:
    branches:
      - main # or use your specific branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # or your preferred Node.js version

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Install Android dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk
          sudo apt install -y gradle
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          curl -sL https://firebase.tools | bash
          firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
            --app your-app-id \
            --groups "testers" \
            --token $FIREBASE_TOKEN
