name: Firebase App Distribution

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Using the latest version

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Create assets directory
      run: mkdir -p android/app/src/main/assets

    - name: Bundle React Native code
      run: |
        npx react-native bundle \
          --platform android \
          --dev false \
          --entry-file index.js \
          --bundle-output android/app/src/main/assets/index.android.bundle \
          --assets-dest android/app/src/main/res/

    - name: Make Gradle executable
      run: chmod +x android/gradlew

    - name: Run Android Build
      run: |
        cd android
        ./gradlew clean
        ./gradlew assembleRelease

    - name: Authenticate with Firebase
      uses: w9jds/firebase-action@v1
      with:
        args: firebase
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}  # Ensure this secret contains the JSON credentials

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Upload APK to Firebase App Distribution
      run: |
        firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --release-notes "Automated release via GitHub Actions" \
          --testers "tester1@example.com,tester2@example.com"
