name: Firebase App Distribution

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Using the latest version

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Create assets directory
      run: mkdir -p android/app/src/main/assets

    - name: Bundle React Native code
      run: |
        npx react-native bundle \
          --platform android \
          --dev false \
          --entry-file index.js \
          --bundle-output android/app/src/main/assets/index.android.bundle \
          --assets-dest android/app/src/main/res/

    - name: Make Gradle executable
      run: chmod +x android/gradlew

    - name: Run Android Build
      run: |
        cd android
        ./gradlew clean
        ./gradlew assembleRelease

    - name: Upload APK to Firebase App Distribution
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      run: |
        ACCESS_TOKEN=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $FIREBASE_API_KEY" \
          https://firebaseappdistribution.googleapis.com/v1alpha/apps/${{ secrets.FIREBASE_APP_ID }}/tokens)

        curl -X POST \
          -F "app_id=${{ secrets.FIREBASE_APP_ID }}" \
          -F "releaseNotes=Automated release via GitHub Actions" \
          -F "testers=tester1@example.com,tester2@example.com" \
          -F "releaseFile=@android/app/build/outputs/apk/release/app-release.apk" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          https://firebaseappdistribution.googleapis.com/v1alpha/apps/${{ secrets.ANDROID_PACKAGE_NAME }}/releases:upload