name: Firebase App Distribution

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Create assets directory
      run: mkdir -p android/app/src/main/assets

    - name: Bundle React Native code
      run: |
        npx react-native bundle \
          --platform android \
          --dev false \
          --entry-file index.js \
          --bundle-output android/app/src/main/assets/index.android.bundle \
          --assets-dest android/app/src/main/res/

    - name: Make Gradle executable
      run: chmod +x android/gradlew

    - name: Set up Firebase credentials
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "$HOME/firebase-service-account.json"
        echo "export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-service-account.json" >> $GITHUB_ENV

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
            with:
              appId: ${{secrets.FIREBASE_APP_ID}}
              #token: ${{secrets.FIREBASE_TOKEN}}   
              serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}      
              groups: testers
              file: app/build/outputs/apk/debug/app-debug.apk      